# Generated by Django 5.0.7 on 2024-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_restaurante', models.IntegerField()),
                ('id_cargo', models.IntegerField()),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('dni', models.IntegerField(db_column='DNI', unique=True)),
                ('usuario', models.CharField(db_column='Usuario', max_length=45, unique=True)),
                ('contraseña', models.CharField(db_column='Contraseña', max_length=45)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
